# Generated by Django 5.1.4 on 2024-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usable_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
